spring.application.name=debezium-oracle-listener-only

# Oracle connection details for Debezium Oracle connector.
app.debezium.connector-name=oracle-embedded-connector
app.debezium.database-hostname=localhost
app.debezium.database-port=1521
app.debezium.database-user=spgy
app.debezium.database-password=9010
app.debezium.database-dbname=ORCL
#app.debezium.database-pdb-name=ORCLPDB

# Comma-separated filters.
app.debezium.schema-include-list=SPGY
app.debezium.table-include-list=SPGY.FRAMEWORK

app.debezium.topic-prefix=oracle-cdc
app.debezium.offset-file-name=data/debezium-offsets.dat
app.debezium.schema-history-file-name=data/debezium-schema-history.dat
snapshot.mode=schema_only
logging.level.com.example.debeziumoracle=INFO

# Retry & DLQ configuration
app.retry-dlq.max-retries=3
app.retry-dlq.initial-backoff-ms=1000
app.retry-dlq.backoff-multiplier=2.0
app.retry-dlq.max-backoff-ms=10000
app.retry-dlq.dlq-file-path=data/dlq
app.retry-dlq.dlq-max-size=10000
