spring.application.name=debezium-oracle-listener-only

# Oracle connection details for Debezium Oracle connector.
app.debezium.connector-name=oracle-embedded-connector
app.debezium.database-hostname=localhost
app.debezium.database-port=1521
app.debezium.database-user=spgy
app.debezium.database-password=9010
app.debezium.database-dbname=ORCL
#app.debezium.database-pdb-name=ORCLPDB

# Comma-separated filters.
app.debezium.schema-include-list=SPGY
app.debezium.table-include-list=SPGY.FRAMEWORK

app.debezium.topic-prefix=oracle-cdc
app.debezium.offset-file-name=data/debezium-offsets.dat
app.debezium.schema-history-file-name=data/debezium-schema-history.dat
snapshot.mode=schema_only
logging.level.com.example.debeziumoracle=INFO